// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ggwvsdzezukxieyjpezu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imdnd3ZzZHplenVreGlleWpwZXp1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU1OTg3MzgsImV4cCI6MjA3MTE3NDczOH0.TUtzuDKpbdTxjd6gOHQo0VlP5Y6VYZI1cr1U_yQjYjE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});